---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-app
  labels:
    app: voting-app
    name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: worker-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: worker-pod
    spec:
      containers:
        - image: kodekloud/examplevotingapp_worker:v1
          name: worker
#       ports:
#         - containerPort: 8000
#     nodeSelector:
#       kubernetes.io/role: worker
