---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: fibo
  labels:
    component: worker
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
        tier: web
    spec:
      containers:
        - name: worker
          image: pataraco/fibo-web-app-worker
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
