---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: fibo
spec:
  accessModes:
    # - ReadOnlyMany
    # - ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
