apiVersion: v1
kind: Service
metadata:
  name: fibo-client
  namespace: testing
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      # nodePort: 31515  # automatically assign a port
  selector:
    component: web
