apiVersion: v1
kind: Pod
metadata:
  name: fibo-client
  labels:
    component: web
  namespace: testing
spec:
  containers:
    - name: client
      image: pataraco/fibo-web-app-client
      ports:
        - containerPort: 3000
