---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: voting-app
  labels:
    app: voting-app
    name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: redis-pod
      # name: redis-rs
      # name: redis
  template:
    metadata:
      labels:
        app: voting-app
        name: redis-pod
        # name: redis-rs
        # name: redis
    spec:
      containers:
        - image: redis
          name: redis
          ports:
            - containerPort: 6379
#     nodeSelector:
#       kubernetes.io/role: worker
