---
apiVersion: v1
kind: Service
metadata:
  # For DNS reasons, must start with alphabetic char
  name: redis
  namespace: voting-app
  labels:
    app: voting-app
    name: redis-service
spec:
  ports:
    # - port: 8001
    - port: 6379
      # protocol: TCP
      targetPort: 6379
  selector:
    # app: redis
    app: voting-app
    name: redis-pod
  type: ClusterIP
