apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      containers:
        - name: client
          # image: gcr.io/google_containers/echoserver:1.4
          image: k8s.gcr.io/echoserver:1.10
          ports:
            - containerPort: 8080
