apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: testing
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      # nodePort: XXXXX  # automaticly randomly assigned (30000-32767)
  selector:
    app: tester
