---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: voting-app
  labels:
    # app: postgres
    app: voting-app
    name: postgres-pod
spec:
  containers:
    - image: postgres
      # name: db
      name: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
