---
apiVersion: v1
kind: Service
metadata:
  # For DNS reasons, must start with alphabetic char
  name: voting-app
  namespace: voting-app
  labels:
    app: voting-app
    name: voting-app-service
spec:
  ports:
    # - port: 8000
    - port: 80
      # protocol: TCP
      targetPort: 80
      nodePort: 30010
  selector:
    app: voting-app
    name: voting-app-pod
  type: NodePort
