---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fibo
  labels:
    component: redis
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
        tier: data
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
