---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  namespace: voting-app
  labels:
    app: voting-app
    name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: result-app-pod
  template:
    metadata:
      labels:
        app: voting-app
        name: result-app-pod
    spec:
      containers:
        - image: kodekloud/examplevotingapp_result:v1
          name: result-app
          ports:
            - containerPort: 80
#     nodeSelector:
#       kubernetes.io/role: worker
