---
apiVersion: v1
kind: Pod
metadata:
  name: result-app
  namespace: voting-app
  labels:
    # app: result-app
    app: voting-app
    name: result-app-pod
spec:
  containers:
    - image: kodekloud/examplevotingapp_result:v1
      name: result-app
      ports:
        - containerPort: 80
