---
apiVersion: v1
kind: Service
metadata:
  # For DNS reasons, must start with alphabetic char
  name: result-app
  namespace: voting-app
  labels:
    app: voting-app
    name: result-app-service
spec:
  ports:
    # - port: 8004
    - port: 80
      # protocol: TCP
      targetPort: 80
      nodePort: 30020
  selector:
    # app: result-app
    app: voting-app
    name: result-app-pod
  type: NodePort
